require('config.colorscheme')
require('config.completion')
require('config.fugitive')
require('config.telescope')
require('config.treesitter')
require('config.galaxyline')
require('config.nerdtree')
require('config.barbar')
