require("config.colorscheme")
require("config.cmp")
require("config.neogit")
require("config.formatter")
require("config.autopairs")
require("config.dashboard")
require("config.telescope")
require("config.treesitter")
require("config.lualine")
-- require("config.feline")
require("config.nvim-tree")
require("config.barbar")
require("config.presence")
-- require("config.saga")
require("config.which-key")
